upstreamProjects:
  Mule-runtime/mule-extensions-parent/1.6.4,
  Mule-runtime/mule-http-service/1.8.4,
  Mule-runtime/mule-oauth-service/2.3.4,
  Mule-runtime/mule-scheduler-service/1.6.4,
  Mule-runtime/mule-soap-service/1.6.4
projectType: runtime
enableMavenTestStage: false
