upstreamProjects:
  Mule-runtime/mule-extensions-parent/support/1.6.x,
  Mule-runtime/mule-http-service/1.8.9,
  Mule-runtime/mule-oauth-service/2.3.9,
  Mule-runtime/mule-scheduler-service/1.6.9,
  Mule-runtime/mule-soap-service/1.6.9
projectType: runtime
enableMavenTestStage: false
