upstreamProjects:
  Mule-runtime/mule-extensions-parent/master,
  Mule-runtime/mule-http-service/support/1.6.x,
  Mule-runtime/mule-oauth-service/support/2.1.x,
  Mule-runtime/mule-scheduler-service/support/1.4.x,
  Mule-runtime/mule-soap-service/master
projectType: runtime
enableMavenTestStage: false
