upstreamProjects:
  Mule-runtime/mule-extensions-parent/master,
  Mule-runtime/mule-http-service/support/1.9.x,
  Mule-runtime/mule-oauth-service/support/2.4.x,
  Mule-runtime/mule-scheduler-service/support/1.7.x,
  Mule-runtime/mule-soap-service/support/1.7.x
projectType: runtime
enableMavenTestStage: false
