upstreamProjects:
  Mule-runtime/mule-extensions-parent/master,
  Mule-runtime/mule-http-service/master,
  Mule-runtime/mule-oauth-service/master,
  Mule-runtime/mule-scheduler-service/master,
  Mule-runtime/mule-soap-service/1.8.1
projectType: runtime
enableMavenTestStage: false
