upstreamProjects:
  Mule-runtime/mule-extensions-parent/support/1.6.x,
  Mule-runtime/mule-http-service/1.8.2,
  Mule-runtime/mule-oauth-service/2.3.2,
  Mule-runtime/mule-scheduler-service/1.6.2,
  Mule-runtime/mule-soap-service/support/1.6.x
projectType: runtime
enableMavenTestStage: false
