upstreamProjects:
  Mule-runtime/mule-extensions-parent/master,
  Mule-runtime/mule-http-service/support/1.11.x,
  Mule-runtime/mule-oauth-service/master,
  Mule-runtime/mule-scheduler-service/support/1.9.x,
  Mule-runtime/mule-soap-service/master
projectType: runtime
enableMavenTestStage: false
