upstreamProjects:
  Mule-runtime/mule-extensions-parent/support/1.7.x,
  Mule-runtime/mule-http-service/1.9.0,
  Mule-runtime/mule-oauth-service/2.4.0,
  Mule-runtime/mule-scheduler-service/1.7.0,
  Mule-runtime/mule-soap-service/1.7.0
projectType: runtime
enableMavenTestStage: false
