upstreamProjects:
  Mule-runtime/mule-extensions-parent/support/1.6.x,
  Mule-runtime/mule-http-service/rel/1.8.4,
  Mule-runtime/mule-oauth-service/rel/2.3.4,
  Mule-runtime/mule-scheduler-service/rel/1.6.4,
  Mule-runtime/mule-soap-service/rel/1.6.4
projectType: runtime
enableMavenTestStage: false
