upstreamProjects:
  Mule-runtime/mule-extensions-parent/support/1.6.x,
  Mule-runtime/mule-http-service/1.8.10,
  Mule-runtime/mule-oauth-service/support/2.3.x,
  Mule-runtime/mule-scheduler-service/1.6.10,
  Mule-runtime/mule-soap-service/support/1.6.x
projectType: runtime
enableMavenTestStage: false
