upstreamProjects:
  Mule-runtime/mule-extensions-parent/1.6.4-DRY-RUN,
  Mule-runtime/mule-http-service/1.8.4-DRY-RUN,
  Mule-runtime/mule-oauth-service/2.3.4-DRY-RUN,
  Mule-runtime/mule-scheduler-service/1.6.4-DRY-RUN,
  Mule-runtime/mule-soap-service/1.6.4-DRY-RUN
projectType: runtime
enableMavenTestStage: false
