upstreamProjects:
  Mule-runtime/mule-extensions-parent/support/1.6.x,
  Mule-runtime/mule-http-service/1.8.8-DRY-RUN,
  Mule-runtime/mule-oauth-service/2.3.8-DRY-RUN,
  Mule-runtime/mule-scheduler-service/1.6.8-DRY-RUN,
  Mule-runtime/mule-soap-service/1.6.8-DRY-RUN
projectType: runtime
enableMavenTestStage: false
