upstreamProjects:
  Mule-runtime/mule-extensions-parent/master,
  Mule-runtime/mule-http-service/support/1.10.x,
  Mule-runtime/mule-oauth-service/support/2.5.x,
  Mule-runtime/mule-scheduler-service/support/1.8.x,
  Mule-runtime/mule-soap-service/master
projectType: runtime
enableMavenTestStage: false
