upstreamProjects:
  Mule-runtime/mule-extensions-parent/support/1.5.x,
  Mule-runtime/mule-http-service/1.7.3,
  Mule-runtime/mule-oauth-service/support/2.2.x,
  Mule-runtime/mule-scheduler-service/1.5.2,
  Mule-runtime/mule-soap-service/support/1.5.x
projectType: runtime
enableMavenTestStage: false
