upstreamProjects:
  Mule-runtime/mule-extensions-parent/1.6.16,
  Mule-runtime/mule-http-service/1.8.17,
  Mule-runtime/mule-oauth-service/2.3.17,
  Mule-runtime/mule-scheduler-service/1.6.17,
  Mule-runtime/mule-soap-service/1.6.17
projectType: runtime
enableMavenTestStage: false
