upstreamProjects:
  Mule-runtime/mule-extensions-parent/1.8.0,
  Mule-runtime/mule-http-service/1.10.0,
  Mule-runtime/mule-oauth-service/2.5.0,
  Mule-runtime/mule-scheduler-service/1.8.0,
  Mule-runtime/mule-soap-service/1.8.0
projectType: runtime
enableMavenTestStage: false
