upstreamProjects:
  Mule-runtime/mule-extensions-parent/1.7.0-DRY-RUN,
  Mule-runtime/mule-http-service/1.9.0-DRY-RUN,
  Mule-runtime/mule-oauth-service/2.4.0-DRY-RUN,
  Mule-runtime/mule-scheduler-service/1.7.0-DRY-RUN,
  Mule-runtime/mule-soap-service/1.7.0-DRY-RUN
projectType: runtime
enableMavenTestStage: false
