upstreamProjects:
  Mule-runtime/mule-extensions-parent/1.7.2,
  Mule-runtime/mule-http-service/1.9.2,
  Mule-runtime/mule-oauth-service/2.4.2,
  Mule-runtime/mule-scheduler-service/1.7.2,
  Mule-runtime/mule-soap-service/1.7.2
projectType: runtime
enableMavenTestStage: false
