upstreamProjects:
  Mule-runtime/mule-extensions-parent/support/1.8.x,
  Mule-runtime/mule-http-service/1.10.1-DRY-RUN,
  Mule-runtime/mule-oauth-service/support/2.5.x,
  Mule-runtime/mule-scheduler-service/support/1.8.x,
  Mule-runtime/mule-soap-service/support/1.8.x
projectType: runtime
enableMavenTestStage: false
