upstreamProjects:
  Mule-runtime/mule-extensions-parent/1.8.0-DRY-RUN,
  Mule-runtime/mule-http-service/1.10.0-DRY-RUN,
  Mule-runtime/mule-oauth-service/2.5.0-DRY-RUN,
  Mule-runtime/mule-scheduler-service/1.8.0-DRY-RUN,
  Mule-runtime/mule-soap-service/1.8.0-DRY-RUN
projectType: runtime
enableMavenTestStage: false
