upstreamProjects:
  Mule-runtime/mule-extensions-parent/1.8.2,
  Mule-runtime/mule-http-service/1.10.2,
  Mule-runtime/mule-oauth-service/2.5.2,
  Mule-runtime/mule-scheduler-service/1.8.2,
  Mule-runtime/mule-soap-service/1.8.2
projectType: runtime
enableMavenTestStage: false
