upstreamProjects:
  Mule-runtime/mule-extensions-parent/master,
  Mule-runtime/mule-http-service/1.11.0,
  Mule-runtime/mule-oauth-service/2.6.0,
  Mule-runtime/mule-scheduler-service/1.9.0,
  Mule-runtime/mule-soap-service/master
projectType: runtime
enableMavenTestStage: false
