upstreamProjects:
  Mule-runtime/mule-extensions-parent/support/1.8.x,
  Mule-runtime/mule-http-service/1.10.0-DRY-RUN,
  Mule-runtime/mule-oauth-service/2.5.0-DRY-RUN,
  Mule-runtime/mule-scheduler-service/1.8.0-DRY-RUN,
  Mule-runtime/mule-soap-service/support/1.8.x
projectType: runtime
enableMavenTestStage: false
