upstreamProjects:
  Mule-runtime/mule-extensions-parent/support/1.7.x,
  Mule-runtime/mule-http-service/1.9.1-DRY-RUN,
  Mule-runtime/mule-oauth-service/support/2.4.x,
  Mule-runtime/mule-scheduler-service/1.7.1-DRY-RUN,
  Mule-runtime/mule-soap-service/support/1.7.x
projectType: runtime
enableMavenTestStage: false
