upstreamProjects:
  Mule-runtime/mule-extensions-parent/support/1.8.x,
  Mule-runtime/mule-http-service/1.10.1,
  Mule-runtime/mule-oauth-service/2.5.1,
  Mule-runtime/mule-scheduler-service/1.8.1,
  Mule-runtime/mule-soap-service/1.8.1
projectType: runtime
enableMavenTestStage: false
