upstreamProjects:
  Mule-runtime/mule-extensions-parent/support/1.6.x,
  Mule-runtime/mule-http-service/rel/1.8.4,
  Mule-runtime/mule-oauth-service/support/2.3.x,
  Mule-runtime/mule-scheduler-service/rel/1.6.4,
  Mule-runtime/mule-soap-service/support/1.6.x
projectType: runtime
enableMavenTestStage: false
