upstreamProjects:
  Mule-runtime/mule-extensions-parent/master,
  Mule-runtime/mule-http-service/master-TESTCYCLE-2020-DRY-RUN,
  Mule-runtime/mule-oauth-service/master,
  Mule-runtime/mule-scheduler-service/master-TESTCYCLE-2020-DRY-RUN,
  Mule-runtime/mule-soap-service/master
projectType: runtime
enableMavenTestStage: false
