upstreamProjects:
  Mule-runtime/mule-extensions-parent/master,
  Mule-runtime/mule-http-service/master-OCTOBER-2024,
  Mule-runtime/mule-oauth-service/master-OCTOBER-2024,
  Mule-runtime/mule-scheduler-service/master-OCTOBER-2024,
  Mule-runtime/mule-soap-service/master-OCTOBER-2024
projectType: runtime
enableMavenTestStage: false
