upstreamProjects:
  Mule-runtime/mule-extensions-parent/master,
  Mule-runtime/mule-http-service/support/1.7.x,
  Mule-runtime/mule-oauth-service/support/2.2.x,
  Mule-runtime/mule-scheduler-service/support/1.5.x,
  Mule-runtime/mule-soap-service/support/1.5.x
projectType: runtime
enableMavenTestStage: false
