upstreamProjects:
  Mule-runtime/mule-extensions-parent/master,
  Mule-runtime/mule-http-service/support/1.5.x,
  Mule-runtime/mule-oauth-service/master,
  Mule-runtime/mule-scheduler-service/support/1.3.x,
  Mule-runtime/mule-soap-service/master
projectType: runtime
enableMavenTestStage: false
