upstreamProjects:
  Mule-runtime/mule-extensions-parent/1.7.4,
  Mule-runtime/mule-http-service/1.9.4,
  Mule-runtime/mule-oauth-service/2.4.4,
  Mule-runtime/mule-scheduler-service/1.7.4,
  Mule-runtime/mule-soap-service/1.7.4
projectType: runtime
enableMavenTestStage: false
