upstreamProjects:
  Mule-runtime/mule-extensions-parent/master-AUGUST-2024,
  Mule-runtime/mule-http-service/master-AUGUST-2024,
  Mule-runtime/mule-oauth-service/master-AUGUST-2024,
  Mule-runtime/mule-scheduler-service/master-AUGUST-2024,
  Mule-runtime/mule-soap-service/master-AUGUST-2024
projectType: runtime
enableMavenTestStage: false
